In [1]:
import numpy as np

In [2]:
np.minimum([2, 3, 4], [1, 5, 2])

array([1, 3, 2])

In [3]:
np.minimum(np.eye(2), [0.5, 2])

array([[0.5, 0. ],
       [0. , 1. ]])

In [4]:
np.minimum([np.nan, 0, np.nan],[0, np.nan, np.nan])

array([nan, nan, nan])

In [5]:
np.minimum(-np.Inf, 1)

-inf